---

target_os: ubuntu
storage_path: /storage
appdata_path: /config

new_disk_prep:
  # - id: /dev/disk/by-id/ata-WDC_WUH721414ALE604_9RG820KC
  # - diskid: /dev/disk/by-id/wwn-0x5000cca27dc2532a
  #   serial: 2SG53JXJ
  # - diskid: /dev/disk/by-id/wwn-0x5000c5008241958f
  #   serial: W4J0EZ8J
  # - diskid: /dev/disk/by-id/wwn-0x5000c500660dde31
  #   serial: Z301BTH7
  # - diskid: /dev/disk/by-id/wwn-0x5000c5006619cb73
  #   serial: Z301ANE1
  # - diskid: /dev/disk/by-id/wwn-0x5000c5007c4e624e
  #   serial: W4J067FX
  # - diskid: /dev/disk/by-id/wwn-0x5000c50082bdd581
  #   serial: W4J0KTWJ`

# disk_to_migrate: S300C5K0

# command to list out disks by label and device id
# lsblk |awk 'NR==1{print $0" DEVICE-ID(S)"}NR>1{dev=$1;gsub("[^[:alnum:]]","",dev);printf $0"\t\t";system("find /dev/disk/by-id -lname \"*"dev"\" -printf \" %p\"");print "";}'
# rsync background command:
# nohup rsync --archive --info=progress2 --remove-source-files /mnt/Z840GYHW/PoolPart.Z840GYHW/ /mnt/Z840HMG7/PoolPart.Z840HMG7 &
# nohup rsync --archive --info=progress2 /mnt/tempssd/docker/volumes/c125675b291cbdec21bd98e2722fd91b5f55f91efb3bfc95b8988f46d41e2294/_data/data/ /storage/Backup/nextcloud_data &

data_disks:
  - { serial: '1906E1E8EBB5', size: '1T', byid: '/dev/disk/by-id/wwn-0x500a0751e1e8ebb5', partsuffix: 'part1', fs: ext4, type: ssd, opts: defaults, state: mounted, content: true }
  - { serial: '2SG53JXJ', size: '7.3T', byid: '/dev/disk/by-id/wwn-0x5000cca27dc2532a', partsuffix: 'part1', fs: ext4, type: hdd, opts: defaults, state: mounted, content: true }
  - { serial: 'ZL2637LS', size: '14.6T', byid: '/dev/disk/by-id/wwn-0x5000c500c60f5838', partsuffix: 'part1', fs: ext4, type: hdd, opts: defaults, state: mounted, content: true }
  - { serial: 'WCT0DX30', size: '7.3T', byid: '/dev/disk/by-id/wwn-0x5000c500acd2f184', partsuffix: 'part1', fs: ext4, type: hdd, opts: defaults, state: mounted, content: true }
  - { serial: 'W4J0KTWJ', size: '4.6T', byid: '/dev/disk/by-id/wwn-0x5000c50082bdd581', partsuffix: 'part1', fs: ext4, type: hdd, opts: defaults, state: mounted, content: true }
  - { serial: 'Z3025Q8K', size: '3.7T', byid: '/dev/disk/by-id/wwn-0x5000c50079015d1a', partsuffix: 'part1', fs: ext4, type: hdd, opts: defaults, state: mounted, content: true }
  - { serial: 'WCT0DH64', size: '7.3T', byid: '/dev/disk/by-id/wwn-0x5000c500ad23afe8', partsuffix: 'part1', fs: ext4, type: hdd, opts: defaults, state: mounted, content: true }
  - { serial: 'S300C5K0', size: '3.7T', byid: '/dev/disk/by-id/wwn-0x5000c5006d93775c', partsuffix: 'part1', fs: ext4, type: hdd, opts: defaults, state: mounted, content: true }
  - { serial: 'Z301ANE1', size: '3.7T', byid: '/dev/disk/by-id/wwn-0x5000c5006619cb73', partsuffix: 'part1', fs: ext4, type: hdd, opts: defaults, state: mounted, content: true }
  - { serial: 'W4J0EZ8J', size: '4.6T', byid: '/dev/disk/by-id/wwn-0x5000c5008241958f', partsuffix: 'part1', fs: ext4, type: hdd, opts: defaults, state: mounted, content: true }
  - { serial: 'W4J067FX', size: '4.6T', byid: '/dev/disk/by-id/wwn-0x5000c5007c4e624e', partsuffix: 'part1', fs: ext4, type: hdd, opts: defaults, state: mounted, content: true }
  - { serial: 'Z301BTH7', size: '3.7T', byid: '/dev/disk/by-id/wwn-0x5000c500660dde31', partsuffix: 'part1', fs: ext4, type: hdd, opts: defaults, state: mounted, content: true }
  - { serial: 'Z840GYHW', size: '7.3T', byid: '/dev/disk/by-id/wwn-0x5000c5009104a265', partsuffix: 'part1', fs: ext4, type: hdd, opts: defaults, state: mounted, content: true }
  - { serial: 'Z840HMG7', size: '7.3T', byid: '/dev/disk/by-id/wwn-0x5000c50091101f86', partsuffix: 'part1', fs: ext4, type: hdd, opts: defaults, state: mounted, content: true }
  - { serial: 'WCT02RKH', size: '7.3T', byid: '/dev/disk/by-id/wwn-0x5000c500aa8efad1', partsuffix: 'part1', fs: ext4, type: hdd, opts: defaults, state: mounted, content: true }
  - { serial: '7SJHSPAW', size: '7.3T', byid: '/dev/disk/by-id/wwn-0x5000cca252e3597f', partsuffix: 'part1', fs: ext4, type: hdd, opts: defaults, state: mounted, content: true }
  - { serial: 'Z301AGLS', size: '3.7T', byid: '/dev/disk/by-id/wwn-0x5000c50065fb324a', partsuffix: 'part1', fs: ext4, type: hdd, opts: defaults, state: mounted, content: true }
  - { serial: '9RG820KC', size: '12.8T', byid: '/dev/disk/by-id/wwn-0x5000cca264c3aa8b', partsuffix: 'part1', fs: ext4, type: hdd, opts: defaults, state: mounted, content: true }
  - { serial: 'ZA2DLYYP', size: '9.1T', byid: '/dev/disk/by-id/wwn-0x5000c500c6dc945f', partsuffix: 'part1', fs: ext4, type: hdd, opts: defaults, state: mounted, content: true }

# when set to true, the mount tasks will recusively chown all files in /storage to 1000/1000
chown_storage: false

#vars for the sprat.mergerfs role
mergerfs_fstab:
  - path: "{{ storage_path }}"
    branches:
      - "/merged/PoolPart.1906E1E8EBB5"
      - "/merged/PoolPart.????????"
    options: "defaults,nonempty,allow_other,use_ino,moveonenospc=true,category.create=ff,dropcacheonclose=true,minfreespace=50G,fsname=mergerfs"
    state: mounted
    passno: 9
  - path: "{{ storage_path }}-fast"
    branches:
      - "/merged/PoolPart.1906E1E8EBB5"
    options: "defaults,nonempty,allow_other,use_ino,moveonenospc=true,category.create=mfs,dropcacheonclose=true,minfreespace=50G,fsname=mergerfs"
    state: mounted
    passno: 9
  - path: "{{ storage_path }}-slow"
    branches:
      - "/merged/PoolPart.????????"
    options: "defaults,nonempty,allow_other,use_ino,moveonenospc=true,category.create=mfs,dropcacheonclose=true,minfreespace=50G,fsname=mergerfs"
    state: mounted
    passno: 9

pip_install_packages:
  - name: docker
  - name: docker-compose

# grog.package
package_list:
  - name: hddtemp
  - name: rsync
  - name: intel-gpu-tools

#forward slashes at the end of src directory matter! with a slash syncs over the contents of the directory
migration_list: []
  # - { src: '/mnt/M14/PoolPart.3fcd95f9-cfb2-4149-afe4-236596bdcb08/', dest: '/storage'}
  # - { src: '/mnt/c/Users/Administrator/AppData/Local/Plex Media Server', dest: '/config/plex/Library/Application Support/Plex Media Server' }
  # - { src: '/mnt/c/Users/Administrator/AppData/Local/qBittorrent/BT_backup', dest: '/config/qbittorrent/qBittorrent' }

# ntfs_migration:
#   - { mount: '/mnt', }
  

# sudo hdparm -y /dev/disk/by-id/wwn-0x5000cca27dc2532a ;\
# sudo hdparm -y /dev/disk/by-id/wwn-0x5000c500c60f5838 ;\
# sudo hdparm -y /dev/disk/by-id/wwn-0x5000c500acd2f184 ;\
# sudo hdparm -y /dev/disk/by-id/wwn-0x5000c50082bdd581 ;\
# sudo hdparm -y /dev/disk/by-id/wwn-0x5000c50079015d1a ;\
# sudo hdparm -y /dev/disk/by-id/wwn-0x5000c500ad23afe8 ;\
# sudo hdparm -y /dev/disk/by-id/wwn-0x5000c5006d93775c ;\
# sudo hdparm -y /dev/disk/by-id/wwn-0x5000c5006619cb73 ;\
# sudo hdparm -y /dev/disk/by-id/wwn-0x5000c5008241958f ;\
# sudo hdparm -y /dev/disk/by-id/wwn-0x5000c5007c4e624e ;\
# sudo hdparm -y /dev/disk/by-id/wwn-0x5000c500660dde31 ;\
# sudo hdparm -y /dev/disk/by-id/wwn-0x5000c5009104a265 ;\
# sudo hdparm -y /dev/disk/by-id/wwn-0x5000c50091101f86 ;\
# sudo hdparm -y /dev/disk/by-id/wwn-0x5000c500aa8efad1 ;\
# sudo hdparm -y /dev/disk/by-id/wwn-0x5000cca252e3597f ;\
# sudo hdparm -y /dev/disk/by-id/wwn-0x5000c50065fb324a ;\
# sudo hdparm -y /dev/disk/by-id/wwn-0x5000cca264c3aa8b ;\
# sudo hdparm -y /dev/disk/by-id/wwn-0x5000c500c6dc945f ;