---
- hosts: mediaserver
  # vars_files:
  #   - 'vars/vault.yaml'
  roles: []
  tasks:

  # - name: migrate list of directories
  #   ansible.posix.synchronize:
  #     src: "{{ item.src }}"
  #     dest: "{{ item.dest }}"
  #     rsync_opts:
  #       - "--remove-source-files"
  #   delegate_to: "{{ inventory_hostname }}"
  #   with_items:
  #     - "{{ migration_list }}"

  # - name: create temppool storage dir ro if not already created
  #   file:
  #     path: "/temppool"
  #     state: directory
  #     mode: "u=ro,g=ro,o=ro"

  # - name: mount mergerfs temp array
  #   mount:
  #     name: "/temppool"
  #     src: "/merged/PoolPart.*"
  #     opts: "defaults,nonempty,allow_other,use_ino,moveonenospc=true,category.create=mfs,dropcacheonclose=true,minfreespace=50G,fsname=mergerfs"
  #     fstype: "fuse.mergerfs"
  #     # change to 'mounted' to auto mount
  #     state: mounted

  - name: remove drive from mergerfs pool
    command: "mergerfs.ctl -m /temppool remove path /merged/PoolPart.{{ item.serial }}"
    loop: "{{ new_disk_prep }}"

  - name: start rsync containers
    community.docker.docker_container:
      name: "transfer_{{ item.serial }}"
      state: started
      image: instrumentisto/rsync-ssh
      entrypoint: rsync
      command: --archive --progress --hard-links /sourcedisk/ /destinationpool
      volumes:
        - "/mnt/{{ item.serial }}/PoolPart.{{ item.serial }}:/sourcedisk"
        - /temppool:/destinationpool
    loop: "{{ new_disk_prep }}"

  
