---
- hosts: mediaserver
  # vars_files:
  #   - 'vars/vault.yaml'
  roles: []
  tasks:

  # - name: migrate list of directories
  #   ansible.posix.synchronize:
  #     src: "{{ item.src }}"
  #     dest: "{{ item.dest }}"
  #     rsync_opts:
  #       - "--remove-source-files"
  #   delegate_to: "{{ inventory_hostname }}"
  #   with_items:
  #     - "{{ migration_list }}"

  # - name: create temppool storage dir ro if not already created
  #   file:
  #     path: "/temppool"
  #     state: directory
  #     mode: "u=rw,g=rw,o=rw"

  # - name: mount mergerfs temp array
  #   mount:
  #     name: "/temppool"
  #     src: "/merged/PoolPart.*"
  #     opts: "defaults,nonempty,allow_other,use_ino,moveonenospc=true,category.create=mfs,dropcacheonclose=true,minfreespace=50G,fsname=mergerfs"
  #     fstype: "fuse.mergerfs"
  #     # change to 'mounted' to auto mount
  #     state: mounted

  # - name: remove drive from mergerfs pool
  #   command: "mergerfs.ctl -m /storage-slow remove path /merged/PoolPart.{{ item.serial }}"
  #   loop: "{{ disks_to_remove }}"

  # - name: start rsync containers
  #   community.docker.docker_container:
  #     name: "transfer_{{ item.serial }}"
  #     state: started
  #     image: instrumentisto/rsync-ssh
  #     entrypoint: rsync
  #     command: -av --progress --hard-links /sourcedisk/ /destinationpool
  #     volumes:
  #       - "/mnt/{{ item.serial }}/PoolPart.{{ item.serial }}:/sourcedisk"
  #       - /mnt/ZR5D67FL/PoolPart.ZR5D67FL:/destinationpool:rw
  #     container_default_behavior: no_defaults
  #   loop: "{{ disks_to_remove }}"

  - name: start rsync containers
    community.docker.docker_container:
      name: "transfer_Z301AGLS"
      state: started
      image: instrumentisto/rsync-ssh
      entrypoint: rsync
      command: -av --progress --hard-links /sourcedisk/ /destinationpool
      volumes:
        - "/temptemp/PoolPart.Z301AGLS:/sourcedisk"
        - /storage-slow:/destinationpool:rw
      container_default_behavior: no_defaults

  - name: start rsync container 2
    community.docker.docker_container:
      name: "transfer_Z3025Q8K"
      state: started
      image: instrumentisto/rsync-ssh
      entrypoint: rsync
      command: -av --progress --hard-links /sourcedisk/ /destinationpool
      volumes:
        - "/temp2/PoolPart.Z3025Q8K:/sourcedisk"
        - /storage-slow:/destinationpool:rw
      container_default_behavior: no_defaults
  
