---
- hosts: mediaserver
  # vars_files:
  #   - 'vars/vault.yaml'
  roles: []
  tasks:
    - name: create gpt partition that fills disk
      community.general.parted:
        device: "{{ item.id }}"
        label: gpt
        name: "{{ item.newPartLabel }}"
        number: 1
        part_start: "0%"
        part_end: "100%"
        state: present
        fs_type: ext4
      with_items:
        - "{{ new_disk_prep }}"
