---
- hosts: mediaserver
  # vars_files:
  #   - 'vars/vault.yaml'
  roles: []
  tasks:

    - name: remove drive from mergerfs pool
      command: mergerfs.ctl remove path /merged/PoolPart.{{ item.serial }}
      loop: "{{ new_disk_prep }}"

    - name: Unmount from /merged
      mount:
        path: /merged/PoolPart.{{ item.serial }}
        state: unmounted
      loop: "{{ new_disk_prep }}"

    - name: Unmount from /mnt
      mount:
        path: /mnt/{{ item.serial }}
        state: unmounted
      loop: "{{ new_disk_prep }}"

    # - name: Reboot machine
    #   reboot:
    #     reboot_timeout: 3600

    - name: wipe disk
      command: wipefs -a {{ item.diskid }}
      loop: "{{ new_disk_prep }}"

    - name: create a new ext4 primary partition
      community.general.parted:
        device: "{{ item.diskid }}"
        label: gpt
        name: "{{ item.serial }}"
        number: 1
        part_start: "0%"
        part_end: "100%"
        state: present
        fs_type: ext4
      loop: "{{ new_disk_prep }}"

    # - name: unmount newly created partition
    #   ansible.posix.mount:
    #     src: "{{ item.diskid }}-part1"
    #     fstype: "ext4"
    #     # change to 'mounted' to auto mount
    #     state: "unmounted"
    #   with_items:
    #     - "{{ new_disk_prep }}"

    # - name: Label the new partition
    #   ansible.builtin.shell:
    #     cmd: "e2label {{ item.diskid }} {{ item.serial }}"
    #   loop: "{{ new_disk_prep }}"

    - name: Create a ext4 filesystem on partition overwriting everything
      community.general.filesystem:
        fstype: ext4
        dev: "{{ item.diskid }}-part1"
        # opts: -cc
        force: yes
      loop: "{{ new_disk_prep }}"