roles:
  - src: geerlingguy.docker
  - src: geerlingguy.pip
  # - src: rossmcdonald.telegraf
# - src: geerlingguy.security
# - src: geerlingguy.ntp
# - src: geerlingguy.github-users
  - src: grog.package
  - src: sprat.mergerfs
  # - src: rossmcdonald.telegraf
# - src: ironicbadger.ansible_role_docker_compose_generator
# - src: ironicbadger.ansible_role_bash_aliases
# - src: ironicbadger.ansible_role_hddtemp
# - src: ironicbadger.ansible_role_snapraid
# - src: ironicbadger.ansible_role_proxmox_nag_removal

# - src: ironicbadger.ansible_users
# - src: weareinteractive.environment

collections:
  - community.general
  - ansible.posix
  - community.docker