---

- hosts: servers
  tasks:
    - name: import keys from github
      authorized_key:  
        user: "{{ ansible_user | default('alex') }}"
        state: present
        key: https://github.com/derekyle.keys
    - name: update all packages
      become: true
      package:
        name: '*'
        state: latest
  