---

- name: ensure hostname is set correctly
  hostname:
    name: "media-server"

- name: disks
  include: disks.yml
  tags:
    - disks

- name: file-sharing
  include: file-sharing.yml
  tags:
    - file-sharing