<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'config_is_read_only' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'datadirectory' => '/data',
  'instanceid' => 'ocdblat2xgz9',
  'passwordsalt' => 'YM/RvtP6k+6+BK/9HjzV7EGodmgWkN',
  'secret' => '0gkTE6FyqqlZUAKlh3tfh7Rf8jvHodbUR8cKOrvCADjTBH3B',
  'overwritehost' => 'cloud.dc5.in',
  'overwriteprotocol' => 'https',
  'trusted_domains' => 
  array (
    0 => 'localhost:9999',
    1 => 'cloud.dc5.in:80',
    2 => 'cloud.dc5.in:443',
    3 => 'cloud.dc5.in',
  ),
  'trusted_proxies' => 
  array (
    0 => '172.18.0.0/16',
    1 => '192.168.1.2',
  ),
  'dbtype' => 'mysql',
  // 'version' => '28.0.4.1',
  'overwrite.cli.url' => 'https://cloud.dc5.in',
  'dbname' => 'nextcloud',
  'dbhost' => 'nextcloud-db',
  'dbport' => '3306',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'Ntr52z8A0wquhH76422gobBNtfeesjnz',
  'installed' => true,
  'maintenance' => false,
  'loglevel' => 1,
  'enable_previews' => true,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\MP3',
    6 => 'OC\\Preview\\TXT',
    7 => 'OC\\Preview\\MarkDown',
    8 => 'OC\\Preview\\OpenDocument',
    9 => 'OC\\Preview\\Krita',
    10 => 'OC\\Preview\\HEIC',
  ),
  'filelocking.enabled' => true,
  'memcache.locking' => '\\OC\\Memcache\\APCu',
  'upgrade.disable-web' => true,
);