http:
  routers:
    router-homeassistant:
      entryPoints:
        - websecure
      rule: Host(`house.dc5.in`)
      service: service-homeassistant
      tls:
        certResolver: myresolver
    router-homeassistant-endpoint:
      entryPoints:
        - websecure
      rule: Host(`alexa-endpoint.dc5.in`)
      service: service-homeassistant
      tls:
        certResolver: myresolver
    # router-unifi:
    #   entryPoints:
    #     - websecure
    #   rule: Host(`unifi.dc5.in`)
    #   service: service-unifi
    #   tls:
    #     certResolver: myresolver
    router-pikvm:
      entryPoints:
        - websecure
      rule: Host(`pikvm.dc5.in`)
      service: service-pikvm
      tls:
        certResolver: myresolver
  services:
    service-homeassistant:
      loadBalancer:
        servers:
        - url: "http://192.168.1.100:8123"
    service-unifi:
      loadBalancer:
        servers:
        - url: "https://192.168.1.100:8443"
    service-pikvm:
      loadBalancer:
        servers:
        - url: "https://192.168.1.122:443"