http:
  routers:
    router-homeassistant:
      entryPoints:
        - websecure
      rule: Host(`ha.ktz.me`)
      service: service-homeassistant
      tls:
        certResolver: cloudflare
    router-blueiris:
      entryPoints:
        - websecure
      rule: Host(`bi.ktz.me`)
      service: service-blueiris
      tls:
        certResolver: cloudflare
    router-octoprint:
      entryPoints:
        - websecure
      rule: Host(`octoprint.ktz.me`)
      service: service-octoprint
      tls:
        certResolver: cloudflare
    router-proxmox:
      entryPoints:
        - websecure
      rule: Host(`proxmox.ktz.lol`)
      service: service-proxmox
      tls:
        certResolver: cloudflare
  services:
    service-homeassistant:
      loadBalancer:
        servers:
        - url: "http://192.168.1.99:8123"
    service-blueiris:
      loadBalancer:
        servers:
        - url: "http://192.168.1.200:81"
    service-octoprint:
      loadBalancer:
        servers:
        - url: "http://192.168.1.90:80"
    service-proxmox:
      loadBalancer:
        servers:
        - url: "http://192.168.1.13:8006"