# - name: Update docker config
#   community.docker.docker_config:
#     name: foo
#     data: Goodnight everyone!
#     labels:
#       bar: baz
#       one: '1'
#     state: present

- name: Create config directory
  file:
    path: "/config"
    state: directory

- name: copy over all container stuff
  copy:
    src: "{{ role_path }}/files/containers/"
    dest: "/config"

- name: create .env file for docker-compose
  copy:
    dest: "/config/.env"
    content: "{{ composer_env }}"

- name: Create and start services
  community.docker.docker_compose:
    project_src: /config
  register: output