---

# - name: create /mnt points
#   file:
#     dest: "{{ item.path }}"
#     state: directory
#     owner: nobody
#     group: nogroup
#     mode: 0777
#   with_items: 
#     - "{{ data_disks }}"

- name: create ro directories on system
  file:
    path: "/merged/{{ item.poolFolder }}"
    state: directory
    mode: "u=ro,g=ro,o=ro"
  loop: "{{ data_disks }}"
  when: item.state == 'mounted'

- name: create main storage dir ro if not already created
  file:
    path: "{{ storage_path }}"
    state: directory
    mode: "u=ro,g=ro,o=ro"

- name: initial mount pool disks
  ansible.posix.mount:
    name: "{{ item.path }}/{{ item.partLabel }}"
    src: "/dev/disk/by-label/{{ item.partLabel }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    # change to 'mounted' to auto mount
    state: "{{ item.state }}"
  loop: "{{ data_disks }}"
  # when: item.path != '/mnt/storage'

- name: bind mount pool mounts
  ansible.posix.mount:
    name: "/merged/{{ item.poolFolder }}"
    src: "{{ item.path }}/{{ item.partLabel }}/{{ item.poolFolder }}"
    fstype: "none"
    opts: "bind"
    # change to 'mounted' to auto mount
    state: "{{ item.state }}"
  loop: "{{ data_disks }}"
  # when: item.path != '/mnt/storage'

- name: Delete empty bind mount directories of unmounted disks
  ansible.builtin.command: "rmdir /merged/{{ item.poolFolder }}"
  loop: "{{ data_disks }}"
  when: item.state == 'unmounted'

- name: Delete empty mount directories of unmounted disks
  ansible.builtin.command: "rmdir /mnt/{{ item.partLabel }}"
  loop: "{{ data_disks }}"
  when: item.state == 'unmounted'

- name: Recursively change ownership of storage pool
  ansible.builtin.file:
    path: "/storage"
    state: directory
    recurse: yes
    owner: 1000
    group: 1000
  when: chown_storage == true


# - name: mount mergerfs array
#   with_items:
#   - "{{ fstab_mergerfs }}"
#   mount:
#     name: "{{ item.mountpoint }}"
#     src: "{{ item.source }}"
#     opts: "{{ item.opts }}"
#     fstype: "{{ item.fs }}"
#     # change to 'mounted' to auto mount
#     state: mounted

