---

- name: ensure hostname is set correctly
  hostname:
    name: "mediaserver"
  tags:
    - init

- name: disks
  include: disks.yml
  tags:
    - disks
    - init
    - mount

- name: install mergerfs-tools
  include: mergerfs-tools.yml
  tags:
    - mergerfs-tools
    - init

- name: install all container apps
  include: container-apps.yml
  tags:
    - container-apps
    - init

- name: file-sharing samba setup
  include: file-sharing.yml
  tags:
    - file-sharing
    - init

# - name: setup nfs share
#   include: nfs.yml
#   tags:
#     - nfs
#     - init