---

- name: ensure hostname is set correctly
  hostname:
    name: "media-server"

- name: disks
  include: disks.yml
  tags:
    - disks

- name: install mergerfs-tools
  include: mergerfs-tools.yml
  tags:
    - mergerfs-tools 

- name: install all container apps
  include: container-apps.yml
  tags:
    - container-apps

# - name: file-sharing
#   include: file-sharing.yml
#   tags:
#     - file-sharing