---
- include_tasks:
    file: install.yml
    apply:
      tags: [telegraf, install]
  tags: [telegraf, install]

- include_tasks:
    file: configure.yml
    apply:
      tags: [telegraf, configure]
  tags: [telegraf, configure]

- include_tasks:
    file: start.yml
    apply:
      tags: [telegraf, start]
  tags: [telegraf, start]
  when: telegraf_start_service
